branches:
  only:
  - python
language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
- 3.4
install:
- pip install -e . "Werkzeug >= 0.9" coverage coveralls
script:
- coverage run --source sass,sassc,sassutils setup.py test
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org:8080#hongminhee"
    on_success: change
    on_failure: always
