branches:
  only:
  - python
language: python
python:
- pypy
- pypy3
- 2.6
- 2.7
- 3.3
- 3.4
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
- pip install -e . "Werkzeug >= 0.9" coverage coveralls
script:
- coverage run --source sass,sassc,sassutils setup.py test
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org:8080#hongminhee"
    on_success: change
    on_failure: always
