branches:
  only:
  - python
language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
script:
- python setup.py test
notifications:
  irc:
    channels:
    - "irc.ozinger.org:8080#hongminhee"
    on_success: change
    on_failure: always
