version: "{build}"
environment:
  global:
    VS90COMNTOOLS: "%VS110COMNTOOLS%"
    VS100COMNTOOLS: "%VS110COMNTOOLS%"
  matrix:
  - PYTHON: "C:\\Python26_32"
    PYTHON_VERSION: "2.6.6"
    PYTHON_ARCH: "32"
  - PYTHON: "C:\\Python27_32"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
  - PYTHON: "C:\\Python33_32"
    PYTHON_VERSION: "3.3.5"
    PYTHON_ARCH: "32"
  - PYTHON: "C:\\Python34_32"
    PYTHON_VERSION: "3.4.1"
    PYTHON_ARCH: "32"
matrix:
  fast_finish: true
init:
- ps: "$env:Path = \"C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\bin;\" + $env:Path"
- "ECHO %PATH%"
- "ECHO %PYTHON%"
- ps: "ls C:/Python*"
install:
- "git -C %APPVEYOR_BUILD_FOLDER% submodule update --init"
- ps: (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/ogrisel/python-appveyor-demo/master/appveyor/install.ps1', 'C:/python-install.ps1')
- "powershell C:/python-install.ps1"
build: false
test_script:
- "dir \"C:\\Program Files (x86)\""
- "%PYTHON%\\python.exe -c \"import os,pprint;pprint.pprint(os.environ)\""
- "%PYTHON%\\python.exe setup.py test"
after_test:
- ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
- "%PYTHON%\\python.exe C:/get-pip.py"
- "%PYTHON%\\Scripts\\pip.exe --version"
- "%PYTHON%\\Scripts\\pip.exe install wheel"
- "%PYTHON%\\python.exe setup.py bdist_wheel"
artifacts:
- path: dist\*
